version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"
    labels: ["dependencies", "ci"]

  - package-ecosystem: gomod
    directory: "/apps/sample-service"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
    labels: ["dependencies", "go"]

  - package-ecosystem: docker
    directory: "/apps/sample-service"
    schedule:
      interval: weekly
    commit-message:
      prefix: "deps"
    labels: ["dependencies", "docker"]

  - package-ecosystem: terraform
    directory: "/terraform/modules/network"
    schedule:
      interval: monthly
    labels: ["dependencies", "terraform"]

  - package-ecosystem: terraform
    directory: "/terraform/modules/eks"
    schedule:
      interval: monthly
    labels: ["dependencies", "terraform"]
