apiVersion: v2
name: kube-prometheus-stack
description: Umbrella chart wrapping kube-prometheus-stack for prod.
type: application
version: 0.1.0
appVersion: "0.76.0"
dependencies:
  - name: kube-prometheus-stack
    version: "62.6.0"
    repository: "https://prometheus-community.github.io/helm-charts"
