external-secrets:
  installCRDs: true

  replicaCount: 3

  serviceAccount:
    create: true
    name: external-secrets
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::123456789012:role/terrascale-prod-external-secrets"

  nodeSelector:
    workload-class: system
  tolerations:
    - key: platform.terrascale.io/system
      operator: Equal
      value: "true"
      effect: NoSchedule

  webhook:
    replicaCount: 3
    nodeSelector:
      workload-class: system
    tolerations:
      - key: platform.terrascale.io/system
        operator: Equal
        value: "true"
        effect: NoSchedule

  certController:
    nodeSelector:
      workload-class: system
    tolerations:
      - key: platform.terrascale.io/system
        operator: Equal
        value: "true"
        effect: NoSchedule
