{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "sample-app.fullname" . }}
  labels: {{- include "sample-app.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ include "sample-app.fullname" . }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.externalSecret.remoteRef.secretKey }}
      remoteRef:
        key: {{ .Values.externalSecret.remoteRef.secretName }}
        property: {{ .Values.externalSecret.remoteRef.secretKey }}
{{- end }}
